version : '3.1'

services:
  drupal:
    image: drupal
    ports: 
      - "8080:80"
    volumes:
      #- ./web:/var/www/html
      - drupal-modules:/var/www/html/modules  
      - drupal-profiles:/var/www/html/profiles  
      - drupal-sites:/var/www/html/sites  
      - drupal-themes:/var/www/html/themes  
    depends_on: 
      - db
  db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=root
    volumes: 
      - pg_data:/var/lib/postgresql/data
volumes: 
 drupal-modules:
 drupal-profiles:
 drupal-sites:
 drupal-themes:
 pg_data: